# Dockerfile with Clang, VS Code (web), a fixed password, and 32-bit libraries
FROM ubuntu:22.04

# Avoid interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# 1. Install system dependencies, Clang compiler, and 32-bit libraries
RUN apt-get update && apt-get install -y \
    nano \
    openssh-server \
    curl \
    sudo \
    build-essential \
    clang \
    gcc-multilib \
    && rm -rf /var/lib/apt/lists/*
    
# Configure SSH server
RUN mkdir /var/run/sshd
# Generate SSH host keys
RUN ssh-keygen -A 

# TODO: REMOVE ON PRODUCTION
# RUN useradd -m -s /bin/bash testing && \
#   echo 'testing:testing' | chpasswd

# Create the restricted users
COPY initialFiles/createRestrictedUsers.sh /tmp/createRestrictedUsers.sh
COPY initialFiles/users.csv /tmp/users.csv
COPY initialFiles/main.c /tmp/main.c
COPY initialFiles/README.md /tmp/README.md
RUN ls /tmp

RUN chmod +x /tmp/createRestrictedUsers.sh \
    && ./tmp/createRestrictedUsers.sh

RUN rm /tmp/createRestrictedUsers.sh \
    && rm /tmp/users.csv \
    && rm /tmp/main.c \
    && rm /tmp/README.md

# 3. Install Node.js (required by code-server) and code-server itself
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs
RUN curl -fsSL https://code-server.dev/install.sh | sh

# Start the SSH service
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]